# Generated by Django 4.2.8 on 2024-03-11 19:19

import django.contrib.auth.validators
import django_countries.fields
from django.db import migrations, models

import authapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0006_alter_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authapp.models.users_avatars_path, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Такой пользователь уже существует'}, help_text='Максимальное значение 15 символов. Используйте только буквы, цифры или знаки +/-/_', max_length=15, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='Мянушка(nickname)'),
        ),
    ]
